### ISSUE TITLE
Currently not every test is successful

### ISSUE THREAD

**Issue by szsascha** [worksofbarry/NetRPG#11]
Hey! Nice idea and project of you! I cloned it immediately after I discovered it.

Unfortunately 2 tests are not working at the moment. 

time_bif_time1.rpgle returns "False" instead of "True"

bif_float.rpgle is printing "Float is not a ready data type."

Maybe they are not important but I think with every commit all tests should work. Maybe I'll take a look at it.

**Comment by worksofliam** [comment]
Hey there!

yes, I am aware of those tests failing and I will fix them up in the next week :)

The `bif_float.rpgle` might be the best place to start! It just needs to implement the float type.

**Comment by worksofliam** [comment]
The float type issue is also at #8.

**Comment by worksofliam** [comment]
The time issue is also at #3.

**Comment by worksofliam** [comment]
I have just fixed the issues remaining in the unit tests and now they're all passing. Woo!
