### ISSUE TITLE
Consider using reflection in a few classes

### ISSUE THREAD

**Issue by szsascha** [worksofbarry/NetRPG#13]
There are a few files where initialization via reflection would be pretty useful.

For example:

Testing.cs - Tests could be loaded and activated via annotation
Function.cs (AddFunctionReference) - Same here. It would be easier to just write the function class and add the RPG keyword via annotation or getter.

But this is only a nice to have ;)

**Comment by worksofliam** [comment]
@SaschaS93 I agree, especially for the unit tests.

You're more than welcome to make a PR to implement one or more of these things - I'd love that actually.

Thanks!

**Comment by szsascha** [comment]
I just created a pull request for the Function.cs stuff. (#16)

Please have a look on it first. I had to create an attribute class and didn't know where I should store it. So I created a new folder.

The search for the correct type is done in two steps. In the first step the method is searching for a type with a name similar to the RPG function. In the second step there is a search with an alias. For example %SCANRPL uses the ScanReplace.cs. There is an annotated alias in The ScanReplace.cs where %SCANRPL is defined. You can use multiple aliases if you have multiple functions which are using the same type. For example %TIMESTAMP, %DATE and %TIME are using all the same Timestamp.cs.

I added the first step just because of the laziness. Maybe it makes more sense to annotate each class, not just those with a different name. But would first like to see how it works in practice. We can still change that afterwards.

For Testing.cs I have the idea to describe the Test in the RPG source as special comment. Maybe like a little scripting language used via the comments with json or something like that. But I'm not sure about that. Maybe it make more sense to create a C# class or method for every test case so the C# tools are useable for testing.

**Comment by worksofliam** [comment]
@SaschaS93 I will close this and let's move this conversation over to the PR.
