### ISSUE TITLE
Implement QSNDDTAQ and QRCVDTAQ

### ISSUE THREAD

**Issue by worksofliam** [worksofbarry/NetRPG#14]
NetRPG has a concept of system APIs called internal APIs, since they are internal to the VM.

It would be cool to create implementations of the `QSNDDTAQ` and `QRCVDTAQ` APIs.

You can see example RPG code here: https://www.mysamplecode.com/2012/03/as400-rpgle-data-queue-tutorial.html

**Comment by szsascha** [comment]
DTAQs are really nice. In the non-i-world there are similar systems called "Message Queues". (Not to be confused with MSGQs from the i-world)

Maybe it make sense to implement an existing system for it. Like RabbitMQ or something other for .NET.

**Comment by worksofliam** [comment]
@SaschaS93 I really like the idea of implementing some like of MQ system over the top of those APIs, but for now I just want to get the basics in.

I made a PR (#22) and am wondering if you can go check it now. I won't merge if you think the implementation is bad. Perhaps we should start with even simpler internal APIs.

Liam
