### ISSUE TITLE
Migrate all ILE sources into one folder

### ISSUE THREAD

**Issue by worksofliam** [worksofbarry/NetRPG#32]
Right now, we have RPG source code in the `RPGCode` directory and all other objects (like JSON tables and display files) in the `objects` folder. I believe we should consolidate all that source into one folder.

This means changing hardcoded paths in the some of the code.

**Comment by szsascha** [comment]
There is a pretty nice solution ;)

https://github.com/SaschaS93/NetRPG/tree/changed-folder-structure

**Comment by worksofliam** [comment]
Agreed! But we some way to remove the need of hard coding the paths. Some library list implementation, which means we also need a place to define the library list D:
